### ISSUE TITLE
图片失效，链接失效等问题

### ISSUE THREAD

**Issue by Beats0** [Beats0/www.mygalgame.com#1]
发现一个有点严重的问题，没过几天就会有一些背景图片失效，原来是被新浪图床和谐掉了，这样严重影响网页浏览效果，正在考虑新的免费图床。_(或许将会使用steam云做图床)_

**Comment by Beats0** [comment]
所有图片转为steam链接，不会再被和谐

**Comment by yukinotech** [comment]
现在图片链接基本还是失效的，但愿找到好的图床

**Comment by Beats0** [comment]
steam图床工具及JavaScript脚本:
https://github.com/Beats0/scripter
