### ISSUE TITLE
博主有这个wordpress主题的链接吗

### ISSUE THREAD

**Issue by oniyakun** [Beats0/www.mygalgame.com#2]
十分喜欢这个主题...希望博主有下载的渠道...十分感谢

**Comment by Beats0** [comment]
wordpress博客主题 ZanBlog3扁平化响应式博客主题
大部分都是用的插件，主题一般需要定制
相关链接: http://www.yeahzan.com/
实例: https://www.mygalgame.com 和 https://www.perfare.net

**Comment by oniyakun** [comment]
好的，谢谢博主

**Comment by Beats0** [comment]
算了，我自己做了一个重构计划：
https://github.com/Beats0/mygalgame
