### ISSUE TITLE
[bug] 图床失效

### ISSUE THREAD

**Issue by orzyyyy** [Beats0/www.mygalgame.com#4]
- <https://ws1.sinaimg.cn/large/005ODKsIgy1figwn1cwmfj30zm0kw0x7.jpg>
图床挂了

**Comment by Beats0** [comment]
新浪图床日常和谐, 以前的图和谐了就难以找回继续维护，所以一般这种情况都没怎么管了
以后图床都开始转向steam图床了，就不用担心和谐问题了
