### ISSUE TITLE
可以请教一下背景图怎么爬的吗

### ISSUE THREAD

**Issue by PerpEternal** [Beats0/www.mygalgame.com#6]
背景图的cookies好像和时间有关

**Comment by Beats0** [comment]
随机数而已
https://github.com/Beats0/www.mygalgame.com/blob/c82410483a0d4a377604a6e31e859874bc4d6e03/js/fade.js#L2589

**Comment by PerpEternal** [comment]
非常感谢

**Comment by PerpEternal** [comment]
额，我指的是你怎么从mygalgame.com上爬的图片

**Comment by Beats0** [comment]
以前有200张的图片包，后来被和谐了就没用了，然后自己加了2500张从yande.re爬的图传到steam图床

**Comment by PerpEternal** [comment]
原来你是站长啊，我以为你是从mygalgame上爬取的数据😂
